[package]
name = "snappy-ui"
version = "0.0.0"
authors = ["Anja Berens <pharaun666@gmail.com>"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
js-sys = "0.3.59"
serde = { version = "1.0.140", features = ["derive"] }
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.32"
web-sys = "0.3.59"
yew = "0.19"

[[bin]]
name = "snappy-ui"
path = "yew/main.rs"

[workspace]
members = ["tauri"]
